image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: “32”
  ANDROID_BUILD_TOOLS: “32.0.0”
  ANDROID_SDK_TOOLS:   “7562133”

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  # use yes to accept all licenses
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/